nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https://.*\.vercel\.app$']
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allow_headers:
            ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
        expose_headers: ["Authorization"]
        max_age: 3600
        allow_credentials: false

    paths:
        "^/api/":
            origin_regex: true
            allow_origin: ['^https://.*\.vercel\.app$']
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            allow_headers:
                ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
            expose_headers: ["Authorization"]
            max_age: 3600
            allow_credentials: false
